// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3VHbzvjdTD63C4dBW0jhcZgr7BUXj84s',
    appId: '1:84034444458:web:87edcca5284de3e4f284d3',
    messagingSenderId: '84034444458',
    projectId: 'profiling-app-1c8e2',
    authDomain: 'profiling-app-1c8e2.firebaseapp.com',
    databaseURL: 'https://profiling-app-1c8e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'profiling-app-1c8e2.appspot.com',
    measurementId: 'G-Q99F4VSYFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuUzirRpaO2QMeUWsUReSY1iwo7NNUxEc',
    appId: '1:84034444458:android:40058b5b57a415f7f284d3',
    messagingSenderId: '84034444458',
    projectId: 'profiling-app-1c8e2',
    databaseURL: 'https://profiling-app-1c8e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'profiling-app-1c8e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiVDSVXrfcDR2tRmApivRjBifY6GyBNg8',
    appId: '1:84034444458:ios:4fdcb5667b8c6535f284d3',
    messagingSenderId: '84034444458',
    projectId: 'profiling-app-1c8e2',
    databaseURL: 'https://profiling-app-1c8e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'profiling-app-1c8e2.appspot.com',
    iosBundleId: 'com.example.profilingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiVDSVXrfcDR2tRmApivRjBifY6GyBNg8',
    appId: '1:84034444458:ios:4fdcb5667b8c6535f284d3',
    messagingSenderId: '84034444458',
    projectId: 'profiling-app-1c8e2',
    databaseURL: 'https://profiling-app-1c8e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'profiling-app-1c8e2.appspot.com',
    iosBundleId: 'com.example.profilingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3VHbzvjdTD63C4dBW0jhcZgr7BUXj84s',
    appId: '1:84034444458:web:a943ad67a9f6b905f284d3',
    messagingSenderId: '84034444458',
    projectId: 'profiling-app-1c8e2',
    authDomain: 'profiling-app-1c8e2.firebaseapp.com',
    databaseURL: 'https://profiling-app-1c8e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'profiling-app-1c8e2.appspot.com',
    measurementId: 'G-M7GMYM9H7G',
  );
}
